test_singly_linked_list: test_singly_linked_list.c linked_list/singly_linked_list/list.c linked_list/singly_linked_list/list.h
	gcc -g -o test_singly_linked_list test_singly_linked_list.c linked_list/singly_linked_list/list.c -I linked_list/singly_linked_list/

test_doubly_linked_list: test_doubly_linked_list.c linked_list/doubly_linked_list/dlist.c linked_list/doubly_linked_list/dlist.h
	gcc -g -o test_doubly_linked_list test_doubly_linked_list.c linked_list/doubly_linked_list/dlist.c -I linked_list/doubly_linked_list/

